### ISSUE TITLE
install-post.sh : chown /var/lib/ceph/osd/*/block*  no such directory

### ISSUE THREAD

**Issue by remedycoin** [extremeshok/xshok-proxmox#11]
Maybe since this is on a fresh install, and I'm not intentionally doing anything with ceph, that might explain the following error: 

chown: cannot access '/var/lib/ceph/osd/*/block*': No such file or directory  

If I understood Ceph better and actually had a cluster of machines setup in the same location, I might try ceph.  

5.4 ISO of Proxmox VE  downloaded 5/12/2019
Downloaded the install-post.sh script also 5/12/2019

**Comment by extremeshok** [comment]
unrelated, I do not execute a chown in the script.

I would assume issues related to the package manager (apt)
