### ISSUE TITLE
install-post.sh  dbus response

### ISSUE THREAD

**Issue by remedycoin** [extremeshok/xshok-proxmox#12]
after 
Processing triggers for dbus (1.10.26-0+deb9u1) ...

this error came up...
**W: APT had planned for dpkg to do more than it reported back (325 vs 516).**    

Proxmox 5.4 iso downloaded 5/12/2019
install-post.sh downloaded 5/12/2019

**Comment by extremeshok** [comment]
unrelated (apt issues, please check the apt logs)
