### ISSUE TITLE
OVH error on raid1 -> required varible not found or the server is already converted to zfs

### ISSUE THREAD

**Issue by Bicet** [extremeshok/xshok-proxmox#13]
I've follow the guide the readme to the letter on ovh installing their Proxmox 5.4-6. 
When I launch the lvm-2-zfs.sh I get this error:

ERROR: required varible not found or the server is already converted to zfs

What am I doing wrong?

```
root@server4:~#  ./lvm-2-zfs.sh && rm lvm-2-zfs.sh
+++++++++++++++++++++++++
WILL DESTROY ALL DATA ON
/var/lib/vz
+++++++++++++++++++++++++
[CTRL]+[C] to exit
+++++++++++++++++++++++++
5..
4..
3..
2..
1..
STARTING CONVERSION
Found partition, continuing
MY_LVM_DEV=/dev/md4
Found raid, continuing
MY_MD_RAID=
Found lv, continuing
MY_LV=
ERROR: required varible not found or the server is already converted to zfs
```

If you need it I can give you access to the OVH manager :)

**Comment by extremeshok** [comment]
These variables were not detected, may i have the output of the following 2 commands

MY_MD_RAID=
MY_LV=

````
pvdisplay
lvdisplay /dev/md4
````

**Comment by extremeshok** [comment]
alas no news...
