### ISSUE TITLE
pve enable lxc docker ??

### ISSUE THREAD

**Issue by jodumont** [extremeshok/xshok-proxmox#14]
Hi again;

on which version of proxmox you use this script (pve-enable-lxc-docker.sh) ?
I don't doubt those manipulation was effective before but on a **Proxmox 5.4-6**
I simply install docker without aufs and bingo **it's working out of the box inside a standard unprivileged debian container**

```
apt-get install -y \
  apt-transport-https \
  ca-certificates curl \
  gnupg2 \
  software-properties-common

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | \
  tee /etc/apt/sources.list.d/docker.list

apt update

apt-get install -y --no-install-recommends \
  containerd.io \
  cgroupfs-mount \
  docker-ce docker-ce-cli \
  libltdl7 \
  git \
  pigz
```

**Comment by extremeshok** [comment]
Use xshok-ubuntu-docker-host.sh script to setup a perfect docker on KVM/quemu

https://github.com/extremeshok/xshok-docker

**Comment by extremeshok** [comment]
I had it working for certain use cases from version 5.0
