### ISSUE TITLE
ZFS Fails on kernel upgrades

### ISSUE THREAD

**Issue by remedycoin** [extremeshok/xshok-proxmox#16]
After installing Proxmox 5.4 with ZFS Raid 0  atop my storage the system boots fine, but after upgrading the kernel, something breaks and I end up with an unbootable system. 

**Reading all physical volumes.  This may take a while …
… zfs: ‘$MY_ZFS_ARC_MIN’ invalid for parameter `zfs_arc_min’
… zfs: `$MY_ZFS_ARC_MAX’ invalid for parameter `zfs_arc_max’

Failed to load ZFS modules.
Manually load the modules and exit.**

The immediate workaround is to boot from an earlier installed kernel which seems to work.  Then edit /etc/modprobe.d/zfs.conf to have direct values for zfs caching values (min & max) . 

Well, I have a 16 GB RAM system so here's some direct values I put into 
/etc/modprobe.d/zfs.conf 
# eXtremeSHOK.com ZFS tuning

# Use 1/16 RAM for MAX cache, 1/8 RAM for MIN cache, or 1GB
**options zfs zfs_arc_min=1073741824
options zfs zfs_arc_max=2147483648**

# use the prefetch method
options zfs l2arc_noprefetch=0

# max write speed to l2arc
# tradeoff between write/read and durability of ssd (?)
# default : 8 * 1024 * 1024
# setting here : 500 * 1024 * 1024
options zfs l2arc_write_max=524288000

**Comment by remedycoin** [comment]
Well pasting the contents of that file didn't look so well.
What ended up making it work was replacing the varrible assignment statements with my own custom calculated values  of
options zfs zfs_arc_min=1073741824
options zfs zfs_arc_max=2147483648
Then I had to run the update command for grub.

**Comment by extremeshok** [comment]
Hi , 

can you please paste the contents of your  new zfs.conf here ?

**Comment by extremeshok** [comment]
please re-open when you have more info for us.

We tested an were unable to recreate the issue.
