### ISSUE TITLE
Hetzner Install

### ISSUE THREAD

**Issue by sinncraft** [extremeshok/xshok-proxmox#17]
` ERROR: You need a /boot partition when using    x
             x software RAID level 0, 5, 6 or 10`

Server has 4 identical drives so its trying to use raid 10

**Comment by sinncraft** [comment]
Also after adding a /boot partition to see if that well help, I noticed that the root/images links need adjusting for example 

`root/images/Debian-95-stretch-64-minimal.tar.gz` needs to now be `root/images/Debian-99-stretch-64-minimal.tar.gz`

**Comment by extremeshok** [comment]
> Also after adding a /boot partition to see if that well help, I noticed that the root/images links need adjusting for example
> 
> `root/images/Debian-95-stretch-64-minimal.tar.gz` needs to now be `root/images/Debian-99-stretch-64-minimal.tar.gz`

Fixed 979f295

**Comment by extremeshok** [comment]
> ` ERROR: You need a /boot partition when using x x software RAID level 0, 5, 6 or 10`
> 
> Server has 4 identical drives so its trying to use raid 10

Fixed  fbd94e2

**Comment by extremeshok** [comment]
Thank you
