### ISSUE TITLE
Hetzner Install Issue

### ISSUE THREAD

**Issue by sinncraft** [extremeshok/xshok-proxmox#19]
Hetzner issue not resolved, When you pull your image location it pulls a Debian image that is not available anymore in the rescue system

**Comment by extremeshok** [comment]
I will be release a new version which will fix this

**Comment by HeIIoween** [comment]
> Hetzner issue not resolved, When you pull your image location it pulls a Debian image that is not available anymore in the rescue system

Because Rescue drops you int to home folder of the root.
Need to cd / and all will work :)

**Comment by connected201** [comment]
> 
> 
> > Hetzner issue not resolved, When you pull your image location it pulls a Debian image that is not available anymore in the rescue system
> 
> Because Rescue drops you into home folder of the root.
> Need to cd / and all will work :)

hi, can you give more explained answer? hetzner script not working, after run i have this message:
![image](https://user-images.githubusercontent.com/20506433/83947169-1c916f80-a81e-11ea-91f6-c352868acd68.png)
