### ISSUE TITLE
ERROR: no devices found for sda3 in /proc/mdstat

### ISSUE THREAD

**Issue by fesch** [extremeshok/xshok-proxmox#2]
Hi,

when I run your script, I get this output:

```
Found partition, continuing

Found raid, continuing
sda3
Found lv, continuing

ERROR: no devices found for sda3 in /proc/mdstat
```

My Proxmox is running on top of a HP server with included RAID controller ...

**Comment by extremeshok** [comment]
Unfortunatly without access to a HP hardware raid server, there is no way I can sort this out.

**Comment by jodumont** [comment]
zfs prefer make is own RAID (soft)
see 1st point : http://www.freenas.org/blog/freenas-worst-practices/
