### ISSUE TITLE
Getting error with network-configure.sh on OVH server

### ISSUE THREAD

**Issue by rizsc** [extremeshok/xshok-proxmox#21]
Hi Extremshock,

I'm getting following error with network-configure.sh script, basically script cannot detect IP, can you please let me know how to resolve this issue?

---------------
 /etc/network/interfaces

### The loopback network interface
auto lo
iface lo inet loopback

### vmbr0: Bridging. Make sure to use only MAC adresses that were assigned to you.
auto vmbr0
iface vmbr0 inet static
        address ###.###.###.###/24
        gateway ###.###.###.254
        bridge_ports enp3s0
        bridge_stp off
        bridge_fd 0

--------------
Generating /etc/default/isc-dhcp-server...
Job for isc-dhcp-server.service failed because the control process exited with error code.
See "systemctl status isc-dhcp-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript isc-dhcp-server, action "start" failed.
* isc-dhcp-server.service - LSB: DHCP server
   Loaded: loaded (/etc/init.d/isc-dhcp-server; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-07-17 01:12:32 UTC; 5ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11642 ExecStart=/etc/init.d/isc-dhcp-server start (code=exited, status=1/FAILURE)
      CPU: 28ms

Jul 17 01:12:30 host2 systemd[1]: Starting LSB: DHCP server...
Jul 17 01:12:30 host2 isc-dhcp-server[11642]: Launching both IPv4 and IPv6 servers (pl…er).
Jul 17 01:12:30 host2 dhcpd[11668]: Wrote 0 leases to leases file.
Jul 17 01:12:32 host2 isc-dhcp-server[11642]: Starting ISC DHCPv4 server: dhcpdcheck s…led!
Jul 17 01:12:32 host2 isc-dhcp-server[11642]:  failed!
Jul 17 01:12:32 host2 systemd[1]: isc-dhcp-server.service: Control process exited, co…tus=1
Jul 17 01:12:32 host2 systemd[1]: Failed to start LSB: DHCP server.
Jul 17 01:12:32 host2 systemd[1]: isc-dhcp-server.service: Unit entered failed state.
Jul 17 01:12:32 host2 systemd[1]: isc-dhcp-server.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for systemd (232-25+deb9u11) ...
Downloading network-addiprange.sh script
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4892  100  4892    0     0  24828      0 --:--:-- --:--:-- --:--:-- 24832
Creating /etc/sysctl.d/99-networking.conf
Auto detecting existing network settings
ERROR: Could not detect all IPv4 varibles
IP:  Netmask: 255.255.255.0 Gateway: 94.23.2.254

Regards,
Riz

**Comment by siteclub** [comment]
Riz, I am facing the same issue. were you able to resolve it?

Best Regards, 

Mukul

**Comment by yorch** [comment]
Same here, just tried to use the script but exact same error, about to start debugging
