### ISSUE TITLE
cat: /sys/block/sda/queue/rotational: No such file or directory

### ISSUE THREAD

**Issue by tinof** [extremeshok/xshok-proxmox#29]
On Hetzner AX-51-nvme

./install-hetzner.sh HOST

RAID ENABLED
RAID Devices: sda,sdb,sdc,sdd
Set RAID level to 10
Detecting and setting optimal swap partition size
cat: /sys/block/sda/queue/rotational: No such file or directory
SSD Detected, RAID 10 enabled, ignoring slog partition
cat: /sys/block/sda/queue/rotational: No such file or directory
SSD Detected, RAID 10 enabled, ignoring cache partition
ERROR: Drive is too small

So the installation does not even start. This happens after first boot to rescue mode as per instructed.

I guess NVMEs are not yet supported?

**Comment by extremeshok** [comment]
I have no access to NVME based servers which I can freely develop on.
