### ISSUE TITLE
duplicate install at line 89 and 95

### ISSUE THREAD

**Issue by jodumont** [extremeshok/xshok-proxmox#3]
Hi;

it is as you which, but for me these two lines did'nt works unless I modified them

see the diff [here](https://github.com/jodumont/proxmox/commit/cf266952b5a37174d3f2f422545695d15a573dc0#diff-7487e5057890ce42f1c27e1129d092a6R92)

;)

**Comment by extremeshok** [comment]
Thank you, fixed in d59475a86bb7a8f165be026dcd7f7274d42cb643
