### ISSUE TITLE
ipset for fail2ban

### ISSUE THREAD

**Issue by jodumont** [extremeshok/xshok-proxmox#4]
hi again;

I would like to propose ipset as default for fail2ban
which is faster than iptables when it come to deal with list of IP

I just don't know how to do a PR with a specific file

https://github.com/jodumont/proxmox/commit/8313015641c7d5908e748211f70ac10cb2f8dc7e#diff-7487e5057890ce42f1c27e1129d092a6

**Comment by extremeshok** [comment]
Hi link gives a 404

Edit the file directly via github web and then save and create a pull request.

**Comment by jodumont** [comment]
https://github.com/extremeshok/xshok-proxmox/pull/5
