### ISSUE TITLE
lvm-2-zfs.sh : ERROR: /var/lib/vz not found (on a NVMe)

### ISSUE THREAD

**Issue by Madydri** [extremeshok/xshok-proxmox#50]
Says 
-----)
STARTING CONVERSION
ERROR: /var/lib/vz not found
(-----
but 
cd /var/lib/
ll
gives
-----)
drwxr-xr-x  7 root    root    4096 Apr  7 01:54 vz/
(-----
Note : on a Debian GNU/Linux 9.13 (stretch)
-----)
[root@**** lib]$ lsblk
NAME                       MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1                    259:0    0 931.5G  0 disk
├─nvme0n1p1                259:1    0     2M  0 part
├─nvme0n1p2                259:2    0     1G  0 part /boot
├─nvme0n1p3                259:3    0     1G  0 part [SWAP]
└─nvme0n1p4                259:4    0 929.5G  0 part
  └─VolGroup00-system_root 253:0    0 929.5G  0 lvm  /
(-----
Thanks !

**Comment by franzos** [comment]
I suppose I'm seeing something similiar:

```bash
./lvm-2-zfs.sh && rm lvm-2-zfs.sh
+++++++++++++++++++++++++
WILL DESTROY ALL DATA ON
/var/lib/vz
+++++++++++++++++++++++++
[CTRL]+[C] to exit
+++++++++++++++++++++++++
5..
4..
3..
2..
1..
STARTING CONVERSION
ERROR: /var/lib/vz not found
```

But the directory exists:

```
ls /var/lib/vz
dump  images  private  snippets  template
```

OS:

```
Linux prox1 5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200) x86_64 GNU/Linux
```
