### ISSUE TITLE
OVH network config

### ISSUE THREAD

**Issue by excitedbox** [extremeshok/xshok-proxmox#52]
The network config script throws an error 
"ERROR: Could not detect all IPv4 varibles
IP:  Netmask: 255.255.255.0 Gateway: redacted"

It does show the right ipv4 ip though. I set the partitions in the manager and had the manager execute the post install script and received no errors. I also ran the zfs script as instructed with no errors and rebooted the server.

**Comment by schulmenueplaner-de** [comment]
@excitedbox, you need to edit network-configure.sh \
and hardcode your IPv4 address like this:

![image](https://user-images.githubusercontent.com/32564853/146172503-d09f25fa-d059-4ba5-9b0a-0925a7839551.png)

**Comment by tracphil** [comment]
@WXpiero same here. did you find a fix?

**Comment by WXpiero** [comment]
> @WXpiero same here. did you find a fix?

no bro,I had to went to that api page ,wrote down my ipv6 info and rewitte the interfaces file manually from scratch.
