### ISSUE TITLE
Problem install on dedicated server Hetzener

### ISSUE THREAD

**Issue by tiberio87** [extremeshok/xshok-proxmox#55]
Hi, when i lauch a script i recive tris error:

root@rescue ~ # ./hetzner-install-proxmox.sh "proxmox.mydomain"
There is no screen to be resumed matching proxmox-install.
--------------------------------
OS: PVE
LVM: TRUE
RAID: 1
BOOT: 1
ROOT: 100
SWAP: 128
ZFS_L2ARC: 0
ZFS_SLOG: 0
Total+1: 230
TARGET_SIZE_GB: 1788
INSTALL_TARGET: nvme0n1,nvme1n1
NVME_COUNT: 2
NVME_TARGET: nvme0n1,nvme1n1
NVME_TARGET_COUNT: 2
SSD_COUNT: 0
SSD_TARGET: 
SSD_TARGET_COUNT: 0
HDD_COUNT: 0
HDD_TARGET: 
HDD_TARGET_COUNT: 0
--------------------------------
--2022-03-29 15:31:13--  https://raw.githubusercontent.com/extremeshok/xshok-proxmox/master/hetzner-install/pve
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-29 15:31:14 ERROR 404: Not Found.

Error: postinstall file was not found: /root/pve

**Comment by extremeshok** [comment]
please try again

**Comment by tinof** [comment]
I made a pull request to fix that: https://github.com/extremeshok/xshok-proxmox/pull/57/commits/6a2f246e28a63c27933280329336069bcbf4bd5a

**Comment by PierpaoloPernici** [comment]
There's also a "swap" on this:
`# INSTALL
if [ "$OS" == "PBS"  ]; then
  INSTALL_COMMAND="${installimage_bin} -a -t yes -i ${installimage_file} -g -s en -x /post-install-proxmox -n ${MY_HOSTNAME} -b grub -d ${INSTALL_TARGET} ${RAID} -p /boot:ext3:${BOOT}G,/:ext4:${ROOT}G${SWAP}${ZFS_L2ARC}${ZFS_SLOG},lvm:pve:all -v pve:data:/var/lib/vz:xfs:all"
else
  INSTALL_COMMAND="${installimage_bin} -a -t yes -i ${installimage_file} -g -s en -x /post-install-proxmox -n ${MY_HOSTNAME} -b grub -d ${INSTALL_TARGET} ${RAID} -p /boot:ext3:${BOOT}G,/:ext4:${ROOT}G${SWAP}${ZFS_L2ARC}${ZFS_SLOG},/backup:xfs:all"
fi`

**Comment by extremeshok** [comment]
fixed
