### ISSUE TITLE
tinc routing issue

### ISSUE THREAD

**Issue by KipourosV** [extremeshok/xshok-proxmox#7]
Hello and thank you for all your hard work.

I 'm testing your tinc script for 2 hosts on seperate networks.

192.168.10.1 host1
192.168.11.1 host2

I can see the vpn is running by pinging between them on the 10.10.1.x network

How can I make them talk by using their hostnames/192.168.x.x addresses?
What am I missing? Do I need to run any of your other scripts? Do I need a new routing rule?

**Comment by extremeshok** [comment]
Edit your hosts file
/etc/hosts
10.10.1.1 host1
10.10.1.1 host2

When creating a cluster , you specifiy the 10.10.1.x ip's for cluster communication

**Comment by KipourosV** [comment]
So host1 /etc/hosts should be changed from:

127.0.0.1 localhost.localdomain localhost
192.168.10.1 host1.domain.com host1 pvelocalhost
192.168.11.1 host2.domain.com host2

to : 

127.0.0.1 localhost.localdomain localhost
10.10.1.1 host1.domain.com host1 pvelocalhost
10.10.1.2 host2.domain.com host2

and host2 hosts file accordingly?
