### ISSUE TITLE
install-post.sh bug 

### ISSUE THREAD

**Issue by stirch** [extremeshok/xshok-proxmox#8]
Hi!
This script failed with such error on fresh installed proxmox 
-------------
Executing: /lib/systemd/systemd-sysv-install enable fail2ban
vm.swappiness = 10
vm.swappiness = 10
vm.min_free_kbytes = 524288
install-post.sh: line 334: syntax error: unexpected end of file
------------------

After removing from script the part about ## Pretty MOTD BANNER  all working how intended

**Comment by jodumont** [comment]
@Orfeous could you decompose the script and run command by command those
because it is the way I'm doing it and I don't any have error but as @stirch mentioned I also don't execute the MOTD BANNER

**Comment by Orfeous** [comment]
@jodumont Sure, will do that.
To bypass the issue i just basically trashed out the whole MOTD part from the script.
For the first look it seems like an identication issue around EOF for the file contents. For some reason the script thinks that one is its own EOF and fails on it.

I'll show you my version and if you like it i create a pr as well.

**Comment by extremeshok** [comment]
@Orfeous please create a PR or post the code change here.

Thanks

**Comment by Orfeous** [comment]
It gave me some headache because i wanted to fix it by keeping the script indentation intact.

At the end i gave up and just "break it" by removing it and adding some space to fix the here-document part.

Now it works. :)
